# OpenAI Models Configuration
models:
  - id: gpt-4
    name: gpt-4
    description: "GPT-4 base model"
    provider: openai
    rate_limits:
      rpm: 200
    parameters:
      temperature: 0.7
      max_tokens: 8192
      
  - id: gpt-3.5-turbo
    name: gpt-3.5-turbo
    description: "GPT-3.5 Turbo base model"
    provider: openai
    rate_limits:
      rpm: 500
    parameters:
      temperature: 0.7
      max_tokens: 4096