# Perplexity Models Configuration
provider: perplexity
models:
  - id: sonar
    name: sonar-small-online
    description: "Sonar small online model"
    provider: perplexity
    rate_limits:
      rpm: 60
    parameters:
      temperature: 0.7
      max_tokens: 1024

  - id: sonar-pro
    name: sonar-medium-online
    description: "Sonar medium online model"
    provider: perplexity
    rate_limits:
      rpm: 120
    parameters:
      temperature: 0.7
      max_tokens: 4096