templates:
  expert_translation:
    template: "Translate the following text from {source_language} to {target_language}:\n\n{text}"
    description: "Professional translation template with expert system context"
    system_message: "You are an expert translator with deep knowledge of both source and target languages, including cultural nuances and context."

  technical_qa:
    template: "Based on the following technical documentation, answer the question:\n\nContext:\n{context}\n\nQuestion: {question}"
    description: "Technical documentation Q&A template"
    system_message: "You are a technical expert who provides clear, accurate, and concise answers based on documentation. Focus on technical accuracy and practical implementation details."

  academic_summarization:
    template: "Provide a {length} summary of the following academic text:\n\n{text}"
    description: "Academic text summarization template"
    system_message: "You are an academic researcher skilled in distilling complex academic content into clear summaries while preserving key technical details and maintaining academic rigor."